### ISSUE TITLE
State denotation

### ISSUE THREAD

**Issue by MusicSole** [maximinus/grateful-dead-songs#2]
I just put in the Venue for Denver Coliseum. I popped in correct info but it is showing up on the list as Denver, CA instead of Denver, CO

**Comment by MusicSole** [comment]
I just put in Balitmore, Maryland and it came up as Baltimore, ME. So it appears there is something not aligned.

**Comment by maximinus** [comment]
Yep, I had a silly bug where when it displayed the state, it actually displayed the next one alphabetically. It all works now!
