### ISSUE TITLE
Master Song List Part 2 

### ISSUE THREAD

**Issue by MusicSole** [maximinus/grateful-dead-songs#21]
1) I can not delete certain titles. And since we are destined to have specific pages built out to each song - it would behoove us to have that Master Song List perfected. 

For instance: I can not delete 26 Miles tunings. I get an error message.

**Comment by maximinus** [comment]
This error:

   column shows_playedsong.seque does not exist

I must have missed a db update on the server,I'll fix this afternoon.

**Comment by maximinus** [comment]
Fixed. The database table migrations were out of sync with the source.

The solution to these types of things moving forward is to leave all migrations in the repo, and ensure we only issue migrate commands to the server code; i.e. do not create any new migrations with server.

Every time the server is updated, perfom a manual "python2.7 manage.py migrate" command to ensure the DB is kept up-to-date.
