### ISSUE TITLE
Enter Set List - part one

### ISSUE THREAD

**Issue by MusicSole** [maximinus/grateful-dead-songs#23]
I put in two fictional shows.

Feels good and easy. 

The encore page did not take - and set two page repeated twice.

**Comment by maximinus** [comment]
When you say the encore page didn't take, do you mean to say that the set
which was selected as an "encore" wasn't saved to the database?

Chris

**Comment by MusicSole** [comment]
Here is a screen shot. 

 I put in Ruben & Cherise for set 3 and checked the box on set three that asks if "set is an encore?"

And set 4 I checked in the box "the set is empty"

I press verify and enter and I get this. 

I attached screenshot. I also sent it regular email if his didn't work.

![screen shot 2015-12-18 at 5 57 37 pm](https://cloud.githubusercontent.com/assets/16036060/11910702/9716cc6a-a5b1-11e5-946e-7f4e824b73e2.png)

**Comment by maximinus** [comment]
Ok. the "Empty Set" checkbox is meant for those times that we know a set was played, but we don't know any of the songs. If you just leave a set totally empty (don't do anything) the set will not be entered into the DB.

But still, it shouldn't repeat, so I'll take a look later.

**Comment by MusicSole** [comment]
Ok

**Comment by maximinus** [comment]
This is being re-written so a set is NOT automatically part of a show, you have to add a set. Then mark as an Encore if needed.

The bug for the repeating set info has been fixed.

**Comment by maximinus** [comment]
I'm closing this big since 1: The code has had an extensive re-write, and 2: I can no longer replicate the bug.
