### ISSUE TITLE
Layout Look

### ISSUE THREAD

**Issue by MusicSole** [maximinus/grateful-dead-songs#24]
![screen shot 2016-01-03 at 10 18 49 pm](https://cloud.githubusercontent.com/assets/16036060/12084432/26686398-b268-11e5-9330-5b46d80a90fe.png)

I'm only seeing forward slashes in between songs. So it appears the seques section is not necessarily functioning.

**Comment by maximinus** [comment]
It's either in the display, or the data input. Will check today.

**Comment by maximinus** [comment]
It's in the input value, so all shows entered so far don't have the correct seque. This is fixed now.

For the time being, I will LEAVE all current show entries in. When it seems that the entering is all OK, I will then delete the current entries and we will start from fresh.
