### ISSUE TITLE
3/15/90

### ISSUE THREAD

**Issue by MusicSole** [maximinus/grateful-dead-songs#25]
I put in this show this afternoon to draw attention to "breakouts".

This show had two. Like everything else that is not a song, fragment or timing, I'm put the info into the comments section.  Obviously, it's not an issue. More of a discussion point about keeping that information and how should we denote it?

Dead Base just had the date it was last played and how many shows since. Would it be difficult to actual calculate the actual time it was since last played?

**Comment by maximinus** [comment]
Anything that can be logically or mathematically inferred from the setlist and show data should not be entered into the comments, as it's a waste of time. The computer can easily work out things like "first time played", "last time played", "longest distance between 2 versions" and so on. You just have to decide what things to look out for, and how they should be displayed.
