### ISSUE TITLE
Shows

### ISSUE THREAD

**Issue by MusicSole** [maximinus/grateful-dead-songs#27]
When you click on shows - it is in random order rather than chronological. 

In other news, project managing a bunch of people's work. 

I should be signing off on three more shows tonight. 

Check out that Not Fade Away from April 30, 1977 right at the 7:42 marker Lesh cues a solid improv jam that showcases that Garcia still had his wits about him. Solid improv. After Summer of 1978 the heroin kicks in.

**Comment by maximinus** [comment]
I know what the problem to this is, but I'm kinda busy over the weekend. The editing tools and this will be fixed by Monday.

**Comment by maximinus** [comment]
Shows are now in chronological order.
