### ISSUE TITLE
Master Song List

### ISSUE THREAD

**Issue by MusicSole** [maximinus/grateful-dead-songs#6]
Chris, 

Everything runs smoothly, easy to understand. 

When I press the enter and verify the data button - it didn't do anything - I didn't see it anywhere on the site - not sure if that was intended at this stage.

I need to make edits to the Master Song List. There are several NRPS songs that need to go plus Deadlists denoted some unorthodox ideas such as "26 Miles tuning" and "Jam" that serve no purpose to our list.

I didn't want to edit them now because I wasn't sure if the work would stick. 

Both Max (my brother) and I had the same experience. Easy to use but couldn't see the work we did. 

A small note - when you go to put in a song the box is highlighted as blue - one time a box turned red and seemed to be frozen. 

Great work, 

Chris

**Comment by maximinus** [comment]
When you click the "verify data" button, you SHOULD get a pop-up message
showing you the structure that you added.

I'll test on my end in a little while. I'm stuck on other work right now,
so I'll update with more instructions tomorrow morning.

Anyway, I'm glad it's pretty easy for the time being. That's a good start,
at least.

Chris

**Comment by maximinus** [comment]
It should work now. see attached photo for what should happen.

If you have issues like this in the future, then you can help me by doing this:

Before you start working with the website in Chrome click on the top right icon and choose 'developer tools' and in the window that comes up select 'console'.

If the website does not appear to be working properly then send me a bug report here and copy what the console said. That'll help me a lot.

![screenshot-grateful dead songs - mozilla firefox](https://cloud.githubusercontent.com/assets/435023/11709737/03adeeac-9f55-11e5-94d1-f0c69fcaf4c1.png)
